### ISSUE TITLE
TypeError when the search is empty

### ISSUE THREAD

**Issue by Themanwithoutaplan** [sarbes/plugin.video.artemediathek#5]
I'm not exactly sure where the code for this is but here's the traceback. If I can find the source, I can probably submit a PR for this.

Arte Mediathek version 2.0.1

2024-01-21 13:17:35.286 T:8216    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.artemediathek/default.py", line 5, in <module>
                                                       arte.action()
                                                     File "/storage/.kodi/addons/script.module.libmediathek4/lib/libmediathek4.py", line 240, in action
                                                       self.addEntries(l)
                                                     File "/storage/.kodi/addons/script.module.libmediathek4/lib/libmediathek4.py", line 56, in addEntries
                                                       for item in d['items']:
                                                                   ~^^^^^^^^^
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--

**Comment by Themanwithoutaplan** [comment]
Moved to https://github.com/sarbes/script.module.libarte/issues/3
