### ISSUE TITLE
Exception when querying Shows by A-Z

### ISSUE THREAD

**Issue by Themanwithoutaplan** [sarbes/plugin.video.artemediathek#6]
Arte Mediathek version 2.0.1

2024-01-21 13:17:35.296 T:834     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.artemediathek/?mode=libMediathekSearch&searchMode=libArteListSearch) failed
2024-01-21 13:17:35.862 T:8218  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-01-21 13:17:56.368 T:8221     info <general>: Skipped 5 duplicate messages..
2024-01-21 13:17:56.368 T:8221    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.JSONDecodeError'>
                                                   Error Contents: Extra data: line 2 column 5 (char 5)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 971, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/site-packages/simplejson/__init__.py", line 525, in loads
                                                     File "/usr/lib/python3.11/site-packages/simplejson/decoder.py", line 375, in decode
                                                   simplejson.errors.JSONDecodeError: Extra data: line 2 column 5 - line 3 column 1 (char 5 - 17)

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.artemediathek/default.py", line 5, in <module>
                                                       arte.action()
                                                     File "/storage/.kodi/addons/script.module.libmediathek4/lib/libmediathek4.py", line 239, in action
                                                       l = self.modes[mode]()
                                                           ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.libarte/lib/libarte.py", line 52, in libArteListData
                                                       return self.parser.parseData(self.params['data'],self.params['uriParams'])
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.libarte/lib/libartewebjsonparser.py", line 43, in parseData
                                                       return self._getData(url)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.libarte/lib/libartewebjsonparser.py", line 46, in _getData
                                                       j = requests.get(url, headers=headers).json()
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 975, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: Extra data: line 2 column 5 (char 5)
                                                   -->End of Python script error report<--

I assume the JSON stream has changed a bit and this is causing an exception upstream in requests.

**Comment by Themanwithoutaplan** [comment]
Moved to https://github.com/sarbes/script.module.libarte/issues/2
